### ISSUE TITLE
code block parsing issue.

### ISSUE THREAD

**Issue by caisj-dev** [alemayhu/notion2anki#230]
hi, there are some parsing issues when there is code block within the notion(see the pic 1), which reports syntax error. Can anyone help me out?
![image](https://user-images.githubusercontent.com/10745051/100458350-92f09980-30fe-11eb-99ea-20368f7548de.png)
here is the error when converting the notion to anki pkg：
![image](https://user-images.githubusercontent.com/10745051/100458384-a4d23c80-30fe-11eb-8d86-e8d214265744.png)

**Comment by aalemayhu** [comment]
@caisj-dev I see you closed this issue. Did you resolve this some other way?

To provide some background:
In order to add support for cloze deletions we tried hard to pick something that
normal people would understand. Normal meaning people are not programmers.
After many rounds of discussions using the code block seemed to make the most
sense to people. 

You can disable the cloze deletion in the card options view https://2anki.net/upload?view=card-options <https://2anki.net/upload?view=card-options>

Happy learning!

- -
Mit freundlichen Grüßen 

Alexander Alemayhu

YouTube: http://youtube.com/c/alexanderalemayhu <http://youtube.com/c/alexanderalemayhu>
Twitch: http://twitch.tv/alexanderalemayhu <http://twitch.tv/alemayhu>
Twitter: https://twitter.com/aalemayhu <https://twitter.com/aalemayhu>

**Comment by aalemayhu** [comment]
Second-pass review (pm): TODO/stub found in relevant code - feature not fully implemented

Evidence: node_modules/.pnpm/@aws-sdk+nested-clients@3.996.21/node_modules/@aws-sdk/nested-clients/dist-types/submodules/sso-oidc/

**Comment by aalemayhu** [comment]
This is from 2020 and the parsing path has been rewritten several times since (the current code-block flow goes through highlight.js with selectable themes). I can't reproduce the original error and there isn't enough detail to pin down the original Notion page. I'm closing it. If you still hit a syntax error converting a Notion page with a code block, reopen with the Notion page (or an export of it) and I'll look again.
