### ISSUE TITLE
Add support for underlined text to appear in the converted anki flashcards.

### ISSUE THREAD

**Issue by jordanyankushev** [alemayhu/notion2anki#233]
Rn when i convert my notion text to anki flashcard the underlined text does not appear on the flashcard. 

I know some CSS so I made a few adjustments and i am happy that when I upload the new cards, the setting i made on the card type stays the same even on the newly added cards. 

Everything else is amazing otherwise.

**Comment by aalemayhu** [comment]
Hei there 👋🏾 

So the issue here is that the export from Notion does not tell us about the underlines. So we are not aware of them. I know this sucks. I am hoping when start supporting using URL's this will be resolved. I can give you a timeline but keep watching this issue and you will get notified.

Thanks 🙂

**Comment by jordanyankushev** [comment]
Ah okay, yes yes I understand. 
Didn’t know it was just a visual thing and not a CSS property that they use in Notion for the underlining. Interesting, indeed. 

Cheers mate, stay healthy! 
Jordan

**Comment by aalemayhu** [comment]
No need to close this, we will keep it open until it gets resolved, thanks!

**Comment by jordanyankushev** [comment]
Hay man!
Btw I just converted some of my new notes from Notion and it seems like I can see the underlined text still underlined in Anki! Well done!

**Comment by aalemayhu** [comment]
Hei Jordan 🙂

I don’t think this is due to any changes I have done. It’s probably Notion which has fixed this issue along with other things.
I will close this one for now. 

Thanks!

Close: #233

- -
Mit freundlichen Grüßen 

Alexander Alemayhu

YouTube: http://youtube.com/c/alexanderalemayhu <http://youtube.com/c/alexanderalemayhu>
Twitch: http://twitch.tv/alexanderalemayhu <http://twitch.tv/alemayhu>
Twitter: https://twitter.com/aalemayhu <https://twitter.com/aalemayhu>
More Links: https://links.alemayhu.com <https://links.alemayhu.com/>
