### ISSUE TITLE
Anki flashcards say - Date created "1970"

### ISSUE THREAD

**Issue by jordanyankushev** [alemayhu/notion2anki#234]
So idk if it is an Anki issue or a Python script issue. 
When I export the cards and add them to Anki I get **date created "1970"**.
![Screen Shot 2020-11-30 at 11 43 03 AM](https://user-images.githubusercontent.com/48214048/100594417-52616d80-3302-11eb-81b6-cf0c8f34d1be.png)

May be in the Python scrip that u use to convert, u need smthing like:

``` python
from datetime import date
today = date.today()
```

If it is an Anki import problem then I have no suggestions :D.

**Comment by aalemayhu** [comment]
Hei there!

I appreciate the effort, but the problem is actually in the project genanki. 
I was looking into getting this resolved and someone has made a solution
to this but the problem is the test suite. See the link below if you are curious,
let's use this issue to keep track of it. 

Related-to: https://github.com/kerrickstaley/genanki/pull/35
